FROM node:16 AS buildjs

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
LABEL version="1.0"

WORKDIR /usr/share/nginx/html
COPY --from=buildjs /usr/src/app/dist/ .

